application: parsemebot
version: 4
runtime: python27
api_version: 1
threadsafe: false

#https://cloud.google.com/appengine/docs/python/config/appconfig#scaling_and_instance_types
#https://cloud.google.com/appengine/docs/python/modules/

#instance_class: B1
#basic_scaling:
#  max_instances: 1
#  idle_timeout: 10m

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /set_webhook
  login: admin
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /languages
  static_dir: languages
  application_readable: true

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest


